channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.1
  - numpy==2.3.2
  - pandas==2.3.2
  - psutil==7.0.0
  - pyarrow==18.1.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env